require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const { GoogleGenAI } = require('@google/genai');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// Initialize Gemini API
const ai = new GoogleGenAI({ 
    apiKey: process.env.GEMINI_API_KEY 
});

// Daleel System Prompt
app.use(express.static('public'));

// Initialize Groq Client
const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY
});

// System Prompt for "Daleel"
const DALEEL_SYSTEM_PROMPT = `
أنت مرشد ذكاء اصطناعي عربي متخصص في التربية غير المنهجية واسمك "دليل".
مهمتك مساعدة المعلمين وقادة المجموعات الشبابية في التخطيط وبناء الأنشطة المدرسية، المبادرات الشبابية، ووضع أفكار لألعاب كسر الجليد.
يجب أن تكون نبرتك إيجابية، مشجعة، واحترافية. قدم إجابات منظمة في نقاط، واستخدم أمثلة عملية إذا لزم الأمر.
لا تخرج عن سياق التربية غير المنهجية، التخطيط التربوي، الأنشطة، وتطوير المهارات.
إذا سئلت عن مواضيع برمجية بحتة أو سياسية أو خارج هذا النطاق، اعتذر بلطف وذكرهم باختصاصك.
`;

// Helper format function, Groq format is the same as OpenAI (role: 'system'/'user'/'assistant', content: string)
function formatMessagesForGroq(conversationHistory) {
    const formattedHistory = [
        {
            role: "system",
            content: DALEEL_SYSTEM_PROMPT
        }
    ];

    for (const msg of conversationHistory) {
        if (msg.role === 'user' || msg.role === 'assistant') {
            formattedHistory.push({
                role: msg.role,
                content: msg.content
            });
        }
    }
    return formattedHistory;
}

// Global variable to keep track of the date
app.post('/api/chat', async (req, res) => {
    try {
        const { messages } = req.body;

        if (!messages || !Array.isArray(messages) || messages.length === 0) {
            return res.status(400).json({ error: "Messages array is required." });
        }

        const formattedMessages = formatMessagesForGroq(messages);

        const chatCompletion = await groq.chat.completions.create({
            messages: formattedMessages,
            model: "llama3-8b-8192", // Using an incredibly fast open-source Llama 3 model
            temperature: 0.7,
            max_tokens: 1024,
            top_p: 1,
            stream: false
        });

        const reply = chatCompletion.choices[0]?.message?.content;
        
        if (!reply) {
            throw new Error("No response generated by Groq.");
        }

        res.json({ reply: reply });

    } catch (error) {
        console.error("Error communicating with Groq API:", error);
        res.status(500).json({
            error: "عذراً، يبدو أن الخادم لا يستجيب في الوقت الحالي. يرجى التأكد من توفر مفتاح GROQ API صحيح."
        });
    }
});

app.listen(port, () => {
    console.log(`Server is running on http://localhost:${port}`);
});